version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8026:8000"
    env_file:
      - ./.env
    restart: always
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
