# Generated by Django 5.1.7 on 2025-05-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_produto', models.CharField(max_length=255, null=True)),
                ('ds_produto', models.TextField(null=True)),
                ('qtd_produto', models.IntegerField(null=True)),
                ('qtd_min_produto', models.IntegerField(blank=True, null=True)),
                ('vl_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dt_create', models.DateTimeField(auto_now_add=True)),
                ('dt_update', models.DateTimeField(auto_now=True)),
                ('dt_deletado', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'produtos',
            },
        ),
    ]
