# Generated by Django 5.1.7 on 2025-05-03 14:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('beneficios', models.JSONField(default=list)),
                ('modo_de_uso', models.JSONField(default=list)),
                ('especificacao', models.JSONField(default=list)),
                ('indicacao', models.JSONField(default=list)),
                ('garatia_de_qualidade', models.TextField()),
                ('preco_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
