# Generated by Django 5.1.7 on 2025-03-09 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0003_produto_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="id_avaliacao",
        ),
    ]
