# Generated by Django 5.1.7 on 2025-03-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nota", models.DecimalField(decimal_places=0, max_digits=1)),
                ("comentario", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
